apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: tanzu-standard-15
  namespace: tanzu-package-repo-global
spec:
  fetch:
    imgpkgBundle:
      image: extensions.aws-usw2.tmc.cloud.vmware.com/packages/standard/repo:v1.6.0-update.1	
