ingress:
  enabled: true
  virtual_host_fqdn: "prometheus.tanzu.devagipi.net"
  prometheus_prefix: "/"
  alertmanager_prefix: "/alertmanager/"
  prometheusServicePort: 80
  alertmanagerServicePort: 80
prometheus:
  pvc:
    storageClassName: "kubernetes-storage-policy"
alertmanager:
  pvc:
    storageClassName: "kubernetes-storage-policy"
